services:
  github-runner:
    build: .
    container_name: github-actions-runner
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ~/runner-worker:/home/actions/_work
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
    restart: unless-stopped
    group_add:
      - 988